### ISSUE TITLE
建议: 在无法访问 nei 的情况下也可以生成工程

### ISSUE THREAD

**Issue by huntbao** [NEYouFan/nei-toolkit#1]
在使用 `nei build` 命令生成`移动端工程`的时候，希望在无法访问 [nei](http://nei.hz.netease.com/) (nei 目前还部署在网易内网，外网暂时无法访问)的情况下也可以生成工程，此时不需要生成 Models 和 Requests 文件资源。

**Comment by agger0207** [comment]
已验证.
