### ISSUE TITLE
改进：希望nei build生成新的iOS工程时不需要去更改build.json文件

### ISSUE THREAD

**Issue by agger0207** [NEYouFan/nei-toolkit#10]
当前build.json文件为
```json
{
	"t": "mobile",
	"l": "oc",
	"w": true,
	"p": "../Stone",
	"tp": "./HTTemplate",
	"resOut": "Stone/Network/", 
	"tdp": "./NEIKey.json"
}
```
而`Stone`实际上可以替换为一个命令行传递的参数ProductName, 这个ProductName也可以用于NEIKey.json中的模板化过程，这样，使用同样的模板文件夹生成新的工程时，不需要去修改build.json文件，可以简化使用。

**Comment by huntbao** [comment]
对于给模板中使用的填充数据，优先级如下：

`命令行参数数据` > `build.json 中的参数数据` > `通过 templateDataPath 参数指定的文件中的数据`

**Comment by huntbao** [comment]
fixed in v0.4.2
