### ISSUE TITLE
安装完毕，nei命令无效

### ISSUE THREAD

**Issue by 1156721874** [NEYouFan/nei-toolkit#104]
执行：sudo npm install nei -g --registry=https://registry.npm.taobao.org
然后使用nei命令：
![image](https://user-images.githubusercontent.com/9300978/59327257-8e260300-8d1b-11e9-91df-7cceb2a12d9a.png)
提示nei指令找不到，请问中间少了什么步骤吗？

**Comment by huntbao** [comment]
QQ 群也有反馈，问题已经由提问者自行修复
