### ISSUE TITLE
测试用例不能执行，难道是我打开方式错误吗？

### ISSUE THREAD

**Issue by donmayun** [NEYouFan/nei-toolkit#105]
你好，网上搜了一大片，怎么感觉没人遇到过我的问题。

在线测试接口，host是自己远程服务器，一直不成功；
1、貌似没有一个开始、run之类的按钮让接口走起来，只有
![LGC( 2FWAU)RZHCC9_M%XHJ](https://user-images.githubusercontent.com/12100492/60226742-1d581c80-98bf-11e9-98ac-aebdd00f2624.png)
这个按钮，用起来有点别扭。点了之后，也不是视频介绍的直接显示测试结果，而是提示了一下“测试开始”，找测试结果去报告页，报告页进入方式貌似也不是很直接。这都是建议，在可接受范围之内~

2、我用的是chrome,应该是最新版，测试的时候是强制要求安装xhr 代理插件的？firefox完全不能运行测试？因为装不了那个xhr插件。那是google的插件的嘛。

3、最不能接受的，插件也装好了，但是就是不通过，貌似页面还是插件有BUG。。
![QC V 1QE(TLUTVN6TOTT889](https://user-images.githubusercontent.com/12100492/60226755-2cd76580-98bf-11e9-969b-d209d54adb19.png)
![%S6$PX4_H` 6B)82{MJ($Z1](https://user-images.githubusercontent.com/12100492/60226759-2fd25600-98bf-11e9-917f-3e31938851b8.png)

**Comment by huntbao** [comment]
插件有问题，已经重新发版
