### ISSUE TITLE
nei build报code403，msg:没有权限

### ISSUE THREAD

**Issue by kimi77** [NEYouFan/nei-toolkit#108]
执行 nei build -k  xyz报错：{code:403,msg:'没有权限'}
![image](https://user-images.githubusercontent.com/9030932/66618622-51581300-ec0c-11e9-8c4c-3d85d9c85f13.png)

另外问一下，这个项目可不可以本地部署和启动，启动后就是
https://nei.netease.com/
官网上的样子

**Comment by kimi77** [comment]
不好意思。这问题太低级了。看了会视频了解了。不过还是想问下有没有办法部署整个nei平台在本地

**Comment by huntbao** [comment]
@kimi77 不能
