### ISSUE TITLE
nei update的时候加参数--view false时，jtr.js里面的tpl不会生成path路径

### ISSUE THREAD

**Issue by triboby** [NEYouFan/nei-toolkit#12]
如题^_^

**Comment by huntbao** [comment]
原因是 jtr.js 文件每次都会重新生成，在 update 的时候如果选择不更新模板，即使用参数  `--view false`，那就不会生成模板路由。

需要调整一下实现逻辑，分离接口和模板的配置。

**Comment by huntbao** [comment]
fixed in v0.4.2
