### ISSUE TITLE
nei构建iOS工程后，模板文件夹中文件的可执行属性丢失

### ISSUE THREAD

**Issue by agger0207** [NEYouFan/nei-toolkit#13]
在模板文件中添加一个可执行的脚本文件，例如CopyMockFiles.sh; 利用nei build命令生成工程后，该文件的可执行属性丢失，执行脚本会报错 "Permission denied".

之前的文件属性为“-rwxrwxrwx”； 生成后的文件属性为"-rw-r--r--"

期望: 可执行的脚本文件在工程生成工程中，可执行属性不丢失，这样可以在工程模板中添加执行脚本的步骤。

**Comment by huntbao** [comment]
fixed in v0.4.2

**Comment by agger0207** [comment]
已验证. iOS工程模板中已可以添加可执行文件.
