### ISSUE TITLE
构建iOS工程增加 productName 参数

### ISSUE THREAD

**Issue by huntbao** [NEYouFan/nei-toolkit#16]
新增加的 productName 参数，默认为 null，必须指定，否则直接报错退出。具体实现过程如下：

1. 如果 `--project` 的值为空，则将它的值设置为 `./{{productName}}`，相对于模板工程目录。如果命令行中有 `--project` 参数，则优先使用命令行中的值，此时的路径也是相对于模板工程目录。
2. resOut 的值更改为  `./{{productName}}/{{resOut}}`，即在它前面追回 productName 的值
3. 模板数据中的 ProductName 修改为相应的值

空白工程要做的修改：

在 iOS 工程模板中，需要将 `--project` 设置为空，`resOut` 参数不要包含 productName 的路径。模板数据文件（NEIKey.json）中的 ProductName 设置为空。build.json 文件内容参考如下：

```json
{
	"t": "mobile",
	"l": "oc",
	"w": true,
	"p": "",
	"tp": "HTSingleView/",
	"tdp": "NEIKey.json",
	"resOut": "Common/Network/"
}
```

**Comment by huntbao** [comment]
fixed in V0.4.4

**Comment by agger0207** [comment]
验证通过.
