### ISSUE TITLE
nei构建mobile工程时默认不需要--resOnly参数

### ISSUE THREAD

**Issue by huntbao** [NEYouFan/nei-toolkit#2]
利用nei构建mobile工程时，有一个可选项，配置是否将模板文件夹下的文件添加到Xcode工程即.xcodeproj文件中；

原有逻辑如下：
1. 默认情况下，不添加额外参数：将模板文件夹下的文件添加到Xcode工程中；
2. 添加--resOnly参数：不将模板文件夹下的文件添加到Xcode工程中；

但实际情况中，一般不需要“将模板文件夹下的文件添加到Xcode工程中；”，这样每次都要加--resOnly参数变得难以理解；

因此，希望将处理逻辑变更如下：

1. 默认情况，不添加额外参数：不将模板文件夹下的文件添加到工程中；
2. 添加额外参数--updateProject: 将模板文件夹下的文件添加到工程中;

**Comment by huntbao** [comment]
调整为“希望的处理逻辑”，由于 `--resOnly` 已经没有用了，所以删除这个参数。

**Comment by agger0207** [comment]
已验证.
