### ISSUE TITLE
nei生成iOS客户端代码时增加对数组类型的支持

### ISSUE THREAD

**Issue by agger0207** [NEYouFan/nei-toolkit#22]
当前nei接口管理平台上，可以直接定义数组类型；但是Objective-C中并没有单独的数组类型，需要转换为NSArray；当前是约定不要直接定义数组类型；而是通过Array<T>的方式来定义数组。

后续希望能增加对数组类型的支持，具体如下：

1. 如果一个数据类型是数组类型，则不要生成对应的Model头文件与实现文件；
2. 如果一个数据类型是数组类型，则在嵌套的Model和Request定义中替换为原有的定义；

例如定义了一个数组类型`StringList`：
![default](https://cloud.githubusercontent.com/assets/5696474/15640597/3b7d429e-266c-11e6-994a-12df1f7be53d.png)

那么在Model和请求中，如果遇到类型`StringList`, 那么生成的Objective-C代码应该是

```Objective-C
@property (nonatomic, strong) NSArray<NSString *> *dataList;
```

而不是

```Objective-C
@property (nonatomic, strong) StringList *dataList;
```

**Comment by huntbao** [comment]
NEI 3.0，策略已调整
