### ISSUE TITLE
手动设置工程的默认生成ftl文件

### ISSUE THREAD

**Issue by sparkmorry** [NEYouFan/nei-toolkit#25]
因为现在做的工程是后来才引入nei的，所以直接update生成的新的ftl文件和原来的页面配置有些冲突，每次都需要手动再去改ftl，所以希望针对每个工程能自己配置生成的ftl、js文件么~~

**Comment by huntbao** [comment]
@sparkmorry update 有个参数 view， 设置为 false 的时候就不会生成 ftl 及相关的文件了。可以看下这个issue  #3

**Comment by sparkmorry** [comment]
@huntbao 但是只能能够关掉 不能手动配置这个生成的文件么~~觉得这个功能是很方便的 如果关掉的话还不如手动加几行代码成本低呢。。本来是想更省力的。。

**Comment by huntbao** [comment]
@sparkmorry 你是指生成的 ftl 和 js 文件可以通过参数指定放在哪个目录吗？

**Comment by sparkmorry** [comment]
@huntbao 不是~是指自己配置ftl里面的内容~

**Comment by huntbao** [comment]
@sparkmorry 新版 NEI 正在重构中，新版可以定制自己的工程规范，到时可以关注一下。工具这一块也会跟进这个需求

**Comment by sparkmorry** [comment]
@huntbao 赞，期待~

**Comment by huntbao** [comment]
NEI 3.0，策略已调整
