### ISSUE TITLE
nei v0.4.8  nei build 产生的默认配置文件有误，导致本地mock失败

### ISSUE THREAD

**Issue by mejustme** [NEYouFan/nei-toolkit#29]
mock/xx/jtr.js 如下：
 
    /* 异步接口mock数据路径 */
    mockApi: '/Users/mejustme/Desktop/workspace/edu-front-2.0/mock/views/'。

    `路径最后应该为：` xxxx/api/

**Comment by huntbao** [comment]
NEI 3.0，策略已调整
