### ISSUE TITLE
iOS端改进需求: 生成Model代码时，希望允许指定Model类的后缀

### ISSUE THREAD

**Issue by agger0207** [NEYouFan/nei-toolkit#30]
需求描述：

1. 生成Model代码时，希望允许指定Model类的后缀，如Model; 例如，nei网站上类型为Person, 前缀为HT, 可以指定在命令中通过参数指定后缀为Model, 则生成的数据类型为HTPersonModel
2. 在第一点的基础上，如果网站定义的数据类型名后缀默认不是Model或者Object, 则加上Model; 即如果nei网站上类型为Person, 那么默认生成为HTPersonModel; 如果类型为PersonModel或者PersonObject, 则不额外添加Model作为后缀，生成的类名为HTPersonModel或者HTPersonObject. 第2个功能实现时尽量做成可开关的；因为不确定所有人都希望默认加Model后缀。

**Comment by huntbao** [comment]
NEI 3.0，策略已调整
