### ISSUE TITLE
新的nei地址无法使用nei

### ISSUE THREAD

**Issue by sammiewy** [NEYouFan/nei-toolkit#33]
如果在新的nei地址上定义接口，http://nei.netease.com/， 数据还是用原来的老的nei地址数据。 新的该怎么用？

**Comment by huntbao** [comment]
新网站上线后，工具需要重新发个版本

**Comment by ZianeCui** [comment]
什么时候发布呢

**Comment by huntbao** [comment]
@ZianeCui @sammiewy 网站已发布，工具也发了

**Comment by huntbao** [comment]
已发布
