### ISSUE TITLE
template4Android 这个构建失败啊

### ISSUE THREAD

**Issue by hunji66** [NEYouFan/nei-toolkit#38]
提示
extname 方法需要传入字符串类型的值

**Comment by huntbao** [comment]
搜索下extname出现的地方，传给它的变量是 undefined 吧，是不是命令行少了什么参数？

**Comment by hunji66** [comment]
那这个template4Android 正确的使用姿势是什么呢？
这个不是demo项目么。。
谢谢啦

**Comment by huntbao** [comment]
@hunji66 你的demo哪里找的啊？要不直接联系下这个 demo 的开发人员？

**Comment by hunji66** [comment]
就是这个网站https://nei.netease.com上 注册完之后Android项目里的。
我以为是官方的demo呢

**Comment by huntbao** [comment]
@hunji66 使用文档已经补上了，你再试下。DEMO 另外有专门的 Android 同事在开发和维护的。

**Comment by hunji66** [comment]
ok 可以了
然后再问一下
http://mp.weixin.qq.com/s?__biz=MzA3ODg4MDk0Ng==&mid=2651112554&idx=1&sn=95e57e0d6cb95f5c209ee8065380a395#rd
这篇文章里面提到的 Android 初始工程及脚手架之类的和NEIPlugin插件是在哪里提供的呢。。
是不是跟这个项目并没有关系？

**Comment by bitterbee** [comment]
@hunji66 
hi，你好，Android 工程模板和 NEIPlugin 插件暂时还在公司内部使用，还没有开放到外面
和 nei-toolkit 是有关系的，主要这里的 NEIPlugin 就是基于 nei-toolkit 编写一个 AndriodStudio 的插件，插件执行其实就是执行了 nei-toolkit 的命令。相当于把命令操作，改成了可视化操作，更方便开发同学使用啦

**Comment by hunji66** [comment]
好的 谢谢啦 😁
@bitterbee

**Comment by mflk007** [comment]
NEIPlugin  为什么不开放呢？。。。文章里写得这么好

**Comment by huntbao** [comment]
@mflk007 插件已发布：https://github.com/NEYouFan/nei-toolkit/blob/master/doc/android_studio.md
