### ISSUE TITLE
异步接口数据类型

### ISSUE THREAD

**Issue by my9074** [NEYouFan/nei-toolkit#41]
期望的数据类型为:
```
{
    code: number,
    data: object,
    msg: string
}
```
但是选择 '导入JSON' 后， data 类型变为 string。请问怎么设置为 Object 类型.
<img width="956" alt="2017-02-13 14 01 39" src="https://cloud.githubusercontent.com/assets/4555635/22872568/2aa9bab0-f1f5-11e6-9b86-643b0999d09b.png">

**Comment by AbnerZheng** [comment]
目前还不能直接通过导入json直接创建object对象。建议将data域创建一个数据类型user， 然后将data指定为user

**Comment by my9074** [comment]
THX

**Comment by my9074** [comment]
感觉这样 对于层次比较深的 Object 不太友好。。每一层都需要定义数据模型

**Comment by AbnerZheng** [comment]
主要是为了强制模型的复用，防止导入的滥用。如果导入json功能自动帮你递归生成下去，那么很容易导致用户之后全部使用导入，而不构建模型。理想的方法是导入json自动解析出是使用哪个模型，但是这个本身是个NP问题，复杂度较高。

也不需要每一层吧，后端代码一般也是有定义数据模型的，两边的数据模型一一对应就好，当然可能需要手动修改。

**Comment by my9074** [comment]
明白，理解了
