### ISSUE TITLE
请求报跨域问题 'Method PUT is not allowed by Access-Control-Allow-Methods in preflight response.'

### ISSUE THREAD

**Issue by my9074** [NEYouFan/nei-toolkit#42]
接口配置如图:
<img width="1079" alt="2017-02-13 16 31 50" src="https://cloud.githubusercontent.com/assets/4555635/22876109/03c75ea6-f20a-11e6-9af3-a133d9a8ce7e.png">

设置完接口后，用`nei server` 起 nodejs 本地接口服务，用 Chrome/Firefox 浏览器发送 PUT 请求，只有 OPTION 方法 没有发送 PUT 请求。console 报跨域的问题。建议直接在 apiResHeaders 下配置允许跨域的那几个标记

<img width="1435" alt="2017-02-13 16 37 19" src="https://cloud.githubusercontent.com/assets/4555635/22876259/bd326386-f20a-11e6-918d-16d7c9893175.png">

<img width="1059" alt="2017-02-13 16 32 01" src="https://cloud.githubusercontent.com/assets/4555635/22876218/7fcf38ca-f20a-11e6-8615-eba773ac15b7.png">

**Comment by AbnerZheng** [comment]
你好， 在运行好nei后，会生成一个nei.{key}的文件夹，里面有server.config.js, 其中的apiResHeaders设置为跨域的标识即可

**Comment by my9074** [comment]
thx
