### ISSUE TITLE
nei server

### ISSUE THREAD

**Issue by wjssxc** [NEYouFan/nei-toolkit#44]
本地容器需要如何创建 ？返回404

**Comment by AbnerZheng** [comment]
[请查看这个](https://github.com/NEYouFan/nei-toolkit/blob/master/doc/%E4%BD%BF%E7%94%A8NEI%E8%BF%9B%E8%A1%8C%E5%89%8D%E5%90%8E%E7%AB%AF%E5%B9%B6%E8%A1%8C%E5%BC%80%E5%8F%91.md)

**Comment by wjssxc** [comment]
谢谢，我重新安装了一遍就好了，之前也是按照那个文档写的弄的。

**Comment by AbnerZheng** [comment]
@wjssxc 是因为版本吗？ 你的nei是不是很久没更新了？

**Comment by luyanchen** [comment]
我也按那个文档弄了，在启动本地模拟容器提示找不到nei项目，请指教，谢谢

**Comment by AbnerZheng** [comment]
@luyanchen 你好，麻烦在你的执行nei路径下把文件夹结构给我看下。

**Comment by luyanchen** [comment]
我用的是工程结构中导入的Node预置模板，然后本地执行nei build -sk key -o todo生成项目，接着nei server -sk key -o todo,提示找不到nei项目

**Comment by AbnerZheng** [comment]
麻烦试着进入todo文件夹，然后执行nei server即可。

**Comment by luyanchen** [comment]
还是提示找不到nei项目。我总共做了一下操作：1.新建工程规范；2.导入Node预置模板；3 本地nei build；4 本地nei server。

**Comment by AbnerZheng** [comment]
我看错了，你这里用的是build sk， 构建工程规范，它是没有接口的，也就是说不是一个工程项目，就不会有mock server功能(mock 应该是对接口的）。所以你要做的是新建一个工程，然后创建响应的接口，再将该工程的工程规范（这个功能在项目的`设置`)设置为该工程规范，这样就可以了

**Comment by luyanchen** [comment]
我说说我的需求吧，本地有一个已经开发好的前端项目。现在想在nei上使用mock服务，让前端可以访问mock数据。然后我在NEI上新建工程，创建接口，并设置了上述工程规范为该工程规范。接下来本地项目如何获取mock数据？请您多指教

**Comment by AbnerZheng** [comment]
接下来，该工程的设置页会有个key，然后你使用nei build -k xxxx(xxx为这个`项目`的key), 之后在生成文件夹中执行nei server，即可。

**Comment by luyanchen** [comment]
nei build -k xxxx 提示权限错误，用nei build -sk xxxx, 在生成文件夹执行nei server还是找不到nei项目

**Comment by AbnerZheng** [comment]
权限错误就用sudo执行。明确一点：sk命令是不会生成mock文件夹的。另外sk和k两个命令所用的key是不一样的，k是项目key，sk是工程规范key

**Comment by luyanchen** [comment]
我的意思是nei server -k key返回的代码是403，没有权限。另外我在项目下未找到项目的key。项目下只有**资源**和**动态**两个tab，没有工具和页面。是否因为没有权限，我用的是网易邮箱登录的。

**Comment by AbnerZheng** [comment]
你的项目名是`公共资源库`吗？ 请新建一个项目， 公共资源库是整个项目组公用的一些资源。

**Comment by AbnerZheng** [comment]
另外你可以通过hzzhenglu在popo上找我

**Comment by luyanchen** [comment]
明白了，项目名确实是公共资源库，按照您的建议已解决了，谢谢您的指教！

**Comment by AbnerZheng** [comment]
不客气
