### ISSUE TITLE
install ht-templates Operation timed out

### ISSUE THREAD

**Issue by tankcong** [NEYouFan/nei-toolkit#45]
安装nei-tooket一切正常，接着安装ht-templates报错：

> Cloning into '/Applications/Android Studio.app/Contents/plugins/android/lib/templates/activities/HTTemplate'...
fatal: unable to access 'https://g.hz.netease.com/hearttouch-android/ht-template.git/': Failed to connect to g.hz.netease.com port 443: Operation timed out
ls: /Applications/Android Studio.app/Contents/plugins/android/lib/templates/activities/HTTemplate: No such file or directory

ping https://g.hz.netease.com没问题
环境：
OS X, 10.12.3
Android Studio 2.3
Build #AI-162.3764568, built on February 24, 2017
JRE: 1.8.0_112-release-b06 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by huntbao** [comment]
@tankcong 你是网易内部用户？

**Comment by tankcong** [comment]
@huntbao 不是的，g.hz.netease.com这个git repo只有内部才能访问吗？

**Comment by huntbao** [comment]
@tankcong 是的，只有公司内部能访问
