### ISSUE TITLE
为什么不提供RPC接口文档管理的功能

### ISSUE THREAD

**Issue by guanxwei** [NEYouFan/nei-toolkit#49]
如题，现在只支持HTTP接口的管理，为什么不提供对诸如RPC服务的接口管理呢？
一般而言，对于RPC服务，我们会希望该管理系统提供以下管理：（当然其他的可以再补充）
（1）服务接口
（2）供外部调用的服务名称
（3）接口参数，包括请求参数和相应参数；对于Java来说，就是一个request和response 类，能够管理这两个类包含哪些参数，什么类型。

**Comment by AbnerZheng** [comment]
你好，
如果仅仅是管理， 目前的nei是可以做到的吧？

**Comment by guanxwei** [comment]
我在创建接口的时候，只有在资源下，有一个异步接口创建的入口，然后请求只有一些HTTP的方法，请问还有其他的入口去创建RPC接口么？而且这些强制必须的不是我想要的啊

**Comment by AbnerZheng** [comment]
NEI目前没有支持rpc的计划，目前的开发重点在版本管理。 
另，一个rpc请求最基本的要素应该是地址、 方法名、 入参和出参。 这些元素在nei上都有，必填项中方法是GET/POST/...不管就好了吧?

**Comment by huntbao** [comment]
已经上线了
