### ISSUE TITLE
NEi 安装失败

### ISSUE THREAD

**Issue by 17782267540** [NEYouFan/nei-toolkit#57]
#![image](https://user-images.githubusercontent.com/28891115/28517337-a256332a-7096-11e7-866b-dce1c797f8f2.png)
Nei 一直安装错我，求解

**Comment by huntbao** [comment]
已经确认是复制粘贴的问题，最后的 -g，前面是横杠 -

**Comment by 17782267540** [comment]
虽然已经找到了，但是还是感谢你的回答
