### ISSUE TITLE
nei构建mobile工程时，NEIKey.json中内容可以命令行参数的形式给出

### ISSUE THREAD

**Issue by agger0207** [NEYouFan/nei-toolkit#6]
当前nei构建mobile工程时，待替换的key值在NEIKey.json中给出。现在应用开发人员反馈希望该信息可以通过命令行命令直接输入而不希望每次去修改NEIKey.json文件.

**Comment by agger0207** [comment]
经讨论，支持的参数不能为任意值；因此考虑增加如下用于模板化的参数：

**Comment by huntbao** [comment]
同 #10
