### ISSUE TITLE
查看文档丢失query参数

### ISSUE THREAD

**Issue by zaiyunduan** [NEYouFan/nei-toolkit#61]
编辑的时候：
```
/path/download?ext=pdf
//范例展示
{
"ext":"pdf"
}
```
但是在查看文档的时，变成：
```
/path/download
//范例展示
{
"ext":"pdf"
}
```
这样会认为参数是通过body传递的。

**Comment by AbnerZheng** [comment]
是网站中的查看文档吗？ 如果是，这个接口的路径是/path/download?ext=pdf吧，那ext如果不在请求数据中加入的话，文档中该路径应该还是/path/download?ext=pdf吧？

**Comment by zaiyunduan** [comment]
@AbnerZheng 编辑的时候，是在请求数据中加入的。编辑状态下，可以看到在路径后自动加上了参数。但查看文档的时候，就没这个参数了

**Comment by AbnerZheng** [comment]
哦哦，看到了，我也同样反馈一下。 多谢
