### ISSUE TITLE
建议增加路径参数说明

### ISSUE THREAD

**Issue by zaiyunduan** [NEYouFan/nei-toolkit#63]

**Comment by AbnerZheng** [comment]
具体是什么意思呢? 能否举个例子？

**Comment by zaiyunduan** [comment]
如：
`/:repo/issues/:issue_id`
增加一个参数说明描述的功能
repo 仓库名称
issue_id 问题id

**Comment by ThoreauZZ** [comment]
这应该是一个必须的功能，请求体和请求头都有说明，请求参数一样需要啊

**Comment by AbnerZheng** [comment]
嗯，这个功能以及基本开发好了。 NEI网站目前在重构，会在重构版本一同上线。

**Comment by huntbao** [comment]
功能已经上线
