### ISSUE TITLE
后端接口数据做签名怎么处理？

### ISSUE THREAD

**Issue by mj19910923** [NEYouFan/nei-toolkit#64]
后端接口数据做签名怎么处理？

**Comment by huntbao** [comment]
@mj19910923 ，你好，能否再说明一下 数据做签名 是指什么意思吗？

**Comment by mj19910923** [comment]
@huntbao 后端接口要求请求数据做签名，怎么在nei中实现呢？

**Comment by huntbao** [comment]
这个估计要自己实现，可以使用规则函数的功能。目前NEI没有提供加密的库文件，如果有需求需要什么js加密库文件，可以回复一下
