### ISSUE TITLE
接口变动会发送POPO和邮件通知吗？

### ISSUE THREAD

**Issue by kajelas** [NEYouFan/nei-toolkit#69]
我注册了一个账号（填写了corp邮箱和popo账号），创建了一个项目和一个接口，然后把自己加入到了这个接口的关注列表中。然后修改接口，并未收到任何邮箱和popo通知。

设置里通知的开关都是打开的。

请问什么条件才会触发邮箱和popo通知？

**Comment by kajelas** [comment]
貌似选择“更新接口需要接口关注者确认”，才会有确认通知？

**Comment by AbnerZheng** [comment]
是这样的。

**Comment by huntbao** [comment]
嗯，需要关注接口才可以
