### ISSUE TITLE
iOS 客户端代码Request生成规则调整

### ISSUE THREAD

**Issue by agger0207** [NEYouFan/nei-toolkit#7]
iOS客户端代码Request生成规则需要作如下调整:

1. 原规则中，request的实现文件中固定包含头文件 `#import "NSObject+HTModel.h"`， 现需更改为`#import "HTNetworking.h"`
2. 原规则中，`responseMapping 方法返回：[{{namePrefix}}{{自定义类型名}} defaultResponseMapping]`更改为 `responseMapping 方法返回：[{{namePrefix}}{{自定义类型名}} ht_modelMapping]`

修改原因：
1. 同nei配套使用的网络库HTNetworking为了支持CocoaPods 0.39，头文件路径作了调整；因此开放出`HTNetworking.h`以引入其他头文件；自动生成的代码尽量直接包含该头文件；
2. 使用者指定Model的基类不为HTHTTPModel时，方法defaultResponseMapping不可用。

注意事项：
由于`HTNetworking`头文件路径的修改不会对老版本生效，因此上述规则的修改应当仅应用于新版本的构建工具，保证老版本的构建工具生成的代码仍然可使用老版本的网络库.

**Comment by huntbao** [comment]
fixed in v0.4.2

**Comment by agger0207** [comment]
已验证.
