### ISSUE TITLE
如何Mock有Query参数的Get方法

### ISSUE THREAD

**Issue by chenzhq** [NEYouFan/nei-toolkit#76]
如题。
例如，有一个API是GET `/v1/users/:id`，根据id查询用户。
现在我需要根据用户名查询用户，设计API GET `/v1/users?name=abc`，但是我build后的Mock服务，这个AP的返回数据I与上面那个是一样的。不知道该是不是哪里设置有问题。

另外，我在请求参数中设置的约束，好像也没有作用，例如 POST `/v1/users`API需要提供相应的data数据，但我用postman测试后发现，有无data数据，结果都一样，似乎只从url进行区分。

以上是我遇到的2个问题，也没有找到相关的issue，故提出。麻烦有时间解答一下，谢谢。

**Comment by huntbao** [comment]
第一个接口，请求地址是：/v1/users/:id
第二个接口，请求地址是：/v1/users，它有一个请求参数name。

这个可以区分的，你再确认一下

**Comment by chenzhq** [comment]
这个我表达有误，我想说的是/v1/users 和 /v1/users?name=abc，会使用同一份mock数据。

**Comment by huntbao** [comment]
请试下在线的版本：[API Mock Online](https://github.com/NEYouFan/nei-toolkit/blob/master/doc/%E8%B0%83%E7%94%A8%E5%9C%A8%E7%BA%BFAPIMock%E6%8E%A5%E5%8F%A3%E8%AF%B4%E6%98%8E.md)
