### ISSUE TITLE
[new feature] 接口编辑页面列表排序

### ISSUE THREAD

**Issue by everywill** [NEYouFan/nei-toolkit#79]
资源->异步接口 列表中可以上移或者下移某个接口

**Comment by huntbao** [comment]
感觉用处不是非常大

**Comment by everywill** [comment]
一期项目开发完成后，二期如果新加接口并且想保持逻辑上关系比较密切的接口靠的比较近，不上移或者下移对应接口应该怎么做？

**Comment by huntbao** [comment]
@everywill，可以把它们放到一个分组里面，或者使用相同的标签
