### ISSUE TITLE
生成iOS客户端请求代码时请求类名规则优化

### ISSUE THREAD

**Issue by agger0207** [NEYouFan/nei-toolkit#8]
## 当前规则

生成的接口类名如下：`{{namePrefix}}{{接口类名}}`

例如：NEI 上的接口类名为 CommentRequest，则生成的类型名字 HTCommentRequest, 头文件名为 HTCommentRequest.h, 实现文件名为 HTCommentRequest.m

## 调整

1. 如果NEI上的接口类名后缀不为`Request`、`Task`, 则自动添加后缀`Request`
例如：NEI 上的接口类名为 Comment，则生成的类型名字仍为 HTCommentRequest, 头文件名为 HTCommentRequest.h, 实现文件名为 HTCommentRequest.m
2. 如果NEI上的接口类名不合法，例如含有中文等等；在按照URL路径生成请求类的同时需要在日志中给出警告，便于开发人员排查问题。

**Comment by huntbao** [comment]
如果接口没有指定类名，会提示： `接口 "InterfaceTest" 没有指定类名, 尝试使用名称`
否则提示：`接口 "InterfaceTest" 的类名 "xxxx" 不合法, 尝试使用名称`

**Comment by huntbao** [comment]
fixed in v0.4.2

**Comment by agger0207** [comment]
已验证.
