### ISSUE TITLE
接口文档预览与接口定义不一致

### ISSUE THREAD

**Issue by changqing1989** [NEYouFan/nei-toolkit#83]
![image](https://user-images.githubusercontent.com/13640778/40641464-4f7538c8-634c-11e8-835b-f51db880266c.png)

选中多个接口，查看文档，有一个接口对应的入参与定义时的不一致。

**Comment by huntbao** [comment]
@changqing1989 , 请问这个接口是什么地址？方便把我加到你的项目中看一下么？

**Comment by changqing1989** [comment]
@huntbao  
![image](https://user-images.githubusercontent.com/13640778/40758826-bbf18fda-64c1-11e8-8a9e-a64cb6c09e69.png) 这个账号是你吗

**Comment by huntbao** [comment]
@changqing1989 ， 是的，你加我下

**Comment by changqing1989** [comment]
@huntbao  不好意思，之前忘记了，今天刚加你了

**Comment by huntbao** [comment]
@changqing1989 现在还不对吗？我这儿看着怎么是对的

**Comment by changqing1989** [comment]
@huntbao  还是不对，出现在多选之后，查看接口文档

**Comment by huntbao** [comment]
@changqing1989 ，多选后，确实是乱了，多谢反馈，接下来会安排修复

**Comment by huntbao** [comment]
线上已经修复这个问题
