### ISSUE TITLE
希望添加模型/API复制功能

### ISSUE THREAD

**Issue by XGHeaven** [NEYouFan/nei-toolkit#85]
有的时候模型直接是类似但是又不同的，每次都要重新写非常麻烦，希望可以直接复制，然后进行修改。

**Comment by huntbao** [comment]
@XGHeaven ，这个功能有的。选中某个数据模型后，看上方的操作栏，有很多操作按钮。

**Comment by XGHeaven** [comment]
好的，谢谢
