### ISSUE TITLE
共享接口希望可以取消共享

### ISSUE THREAD

**Issue by illidantao** [NEYouFan/nei-toolkit#88]
会在分组内到处乱串，如果是所有项目都用到，请在开启共享的时候提示

**Comment by huntbao** [comment]
@illidantao 没有直接取消共享的功能。可以先将它复制到目标项目，然后在公共资源库将它删除。

一定要先确认复制成功了，别误删除了

**Comment by huntbao** [comment]
@illidantao 提示文案已经做了修改，感谢提醒。
