### ISSUE TITLE
nei枚举类型区分字符串还是整型

### ISSUE THREAD

**Issue by agger0207** [NEYouFan/nei-toolkit#9]
当前nei接口管理平台对于枚举类型都当作字符串来处理，iOS客户端使用起来没有那么方便；但是由于Objective-C的枚举NSEnum无法描述字符串，所以希望接口描述里面可以有办法区分是字符串还是整型。对于字符串，仍然按照原有规则生成；对于整型，后续期待可以生成类似如下的代码：
```objective-c
typedef NS_ENUM(NSInteger, {{namePrefix}}{{类型名}}) {
	{{namePrefix}}{{类型名}}{{枚举的 key1}} ＝ {{枚举的 key1 的值}},  // {{枚举的key1的描述}}
	 {{namePrefix}}{{类型名}}{{枚举的 key2}} ＝ {{枚举的 key2 的值}},  // {{枚举的key2的描述}}
	 {{namePrefix}}{{类型名}}{{枚举的 key3}} ＝ {{枚举的 key3 的值}},  // {{枚举的key3的描述}}
};
```

**Comment by huntbao** [comment]
这是 NEI 网站的问题，已在 NEI 中创建，见 [https://github.com/NEYouFan/nei-platform/issues/5](https://github.com/NEYouFan/nei-platform/issues/5)
