### ISSUE TITLE
JSON注释自动添加到描述字段

### ISSUE THREAD

**Issue by tunzao** [NEYouFan/nei-toolkit#93]
导入JSON时，在每个字段后都添加了备注信息，希望解析时能把备注添加到描述字段上，JSON数据如下：

```json
{
"id":123, // 自增id
"taskName":"test task" // 任务名称，必须
}
```

**Comment by huntbao** [comment]
这个就不是合法的 JSON 了，合法的 JSON 是不能加注释的

**Comment by tunzao** [comment]
因为你们把带注释的json给合法的处理了，不由得让人想要更多😂


________________________________
收件人: HuntBao <notifications@github.com>
发送时间: 星期四, 十一月 15, 2018 20:51
收件人: NEYouFan/nei-toolkit
抄送: tunzao; Author
主题: Re: [NEYouFan/nei-toolkit] JSON注释自动添加到描述字段 (#93)


这个就不是合法的 JSON 了，合法的 JSON 是不能加注释的
