### ISSUE TITLE
我的账号无法登陆，也无法注册，但是我同事的账号在我电脑上却可以登陆

### ISSUE THREAD

**Issue by namxedoc** [NEYouFan/nei-toolkit#94]
![image](https://user-images.githubusercontent.com/22809336/49274441-5fe58200-f4b3-11e8-91d7-08fcc4ad653c.png)
我登陆注册都会显示 这个错 我试过火狐谷歌safari 都不行，版本都是新的，浏览器设置都重置过，cookie缓存都清理过。。。

**Comment by huntbao** [comment]
这两天会解决这个问题

**Comment by huntbao** [comment]
@namxedoc 已经修复，请验证
