### ISSUE TITLE
数据模型默认值导入时不起作用

### ISSUE THREAD

**Issue by LittleClown** [NEYouFan/nei-toolkit#95]
hey，
导入数据模型时，默认值不起作用，使用的数据如下：
```json
{
  "name": "A",
  "format": 0,
  "description": "ss",
  "tag": "",
  "params": [
    {
      "name": "name",
      "typeName": "String",
      "description": "姓名",
      "defaultValue": "",
      "isArray": 0
    },
    {
      "name": "age",
      "typeName": "Number",
      "description": "年龄",
      "defaultValue": "null",
      "isArray": 0
    }
  ]
}
```

**Comment by huntbao** [comment]
导入 json 的时候，如果类型是数组，则取数组第一个元素的值。第一个元素的 `defaultValue` 是空字符串。

**Comment by LittleClown** [comment]
额，isArray: 0 不是表示非数组吗？没明白你的意思。
可能是我没表述好，现在是希望默认值可以表现出 null，如我上面的例子中，怎么样才能使得 age 的默认值显示为 null 呢？

**Comment by huntbao** [comment]
在解析 params 的时候，因为它是一个数组，数组元素的类型一般都是一样的，所以只取了第一个元素来解析，也就是：
```
{
      "name": "name",
      "typeName": "String",
      "description": "姓名",
      "defaultValue": "",
      "isArray": 0
}
```
想要使得 age 的默认值显示为 null 呢，这样就可以了：
```
{
  "name": "A",
  "format": 0,
  "description": "ss",
  "tag": "",
  "params": [
    {
      "name": "name",
      "typeName": "String",
      "description": "姓名",
      "defaultValue": "null",
      "isArray": 0
    }
  ]
}
```

**Comment by LittleClown** [comment]
我觉得你说的有问题，场景是在 nei 中导入模型：

  * format = 0 就是声明为 hash 对象了
  * params 是自定hash对象的属性，而不是说一个属性类型为 array （或者我没正确理解你的意思？）

见下图（可见我的用法应该是没有问题的）：
![image](https://user-images.githubusercontent.com/14110615/50536690-f92ab580-0b91-11e9-8b79-41a111f96517.png)

然后在创建之后，看到的却是
![image](https://user-images.githubusercontent.com/14110615/50536705-1f505580-0b92-11e9-8697-8f35d0777be8.png)
默认值直接丢失了

**Comment by LittleClown** [comment]
导入操作是从这里进入的：

![image](https://user-images.githubusercontent.com/14110615/50536738-72c2a380-0b92-11e9-9306-2d5766fe8078.png)

**Comment by LittleClown** [comment]
你好，可能我前面表述的不够清晰，我试着重新说明一下：

### 使用场景
创建一个哈希模型，其某个属性 x 的默认值可以置为 null 或 []，这样前端同学就能知道该如何处理这个字段了（即是否假定始终能作为一个数组使用）

### 现在的问题
通过 json 导入时，预览界面能看到默认值，而创建出来的数据模型默认值丢失

**Comment by huntbao** [comment]
@LittleClown 默认值是根据类型来转换的，`"null"` 这个转换成 `Number`，转换不出来

**Comment by huntbao** [comment]
@LittleClown 已经修复上线，请验证

**Comment by LittleClown** [comment]
正常了，感谢！
