### ISSUE TITLE
测试用例，域名保存403报错

### ISSUE THREAD

**Issue by liyingfang** [NEYouFan/nei-toolkit#97]
设置添加测试服务器域名，保存时请求响应：{"code":403,"result":{"rid":38392,"uid":20021},"msg":"[object Object]"}

**Comment by huntbao** [comment]
信息太少，无法排查。请提供具体步骤，包括项目信息。可以私下发我邮箱：huntbao@126.com，或者加官方的 qq 群找我私聊

**Comment by huntbao** [comment]
是角色权限问题，观察者没有权限，关闭了
